### PR TITLE
Web/function/submit application

### LINKED ISSUE #106: Submit application function
Cloud function with reCAPTCHA integration.

### PR DESCRIPTION
**Pull request by chamkank**
:tickets: **Ticket(s)**: Closes #106 

---

## :construction_worker: Changes
- Added submission function to front-end
- Added submission function to back-end
- Added `make dev` and `make prod`
  - `make dev` will run `make web` and `make functions` in parallel, so it will locally host the front-end as usual and also emulate the cloud functions locally. All requests to cloud functions made from the front-end will automatically be made to the local cloud functions (which run on `localhost:5000`).
- `make prod` will run `make build` and `make deploy-prod` in parallel, so it will build the app into `/docs/` like usual, but also publish the cloud functions to our production environment

[Demo gif of `make dev` and submitting an application](https://i.imgur.com/eQKc3hD.gif)

## :thought_balloon: Notes (updated)
- reCAPTCHA is now fully implemented
- The function writes everything to two separate collections, `hacker_quick_info` and `hacker_main_info`. It also uses `validate.js`, and the constraints will need to be finalized with #158 

## :flashlight: Testing Instructions
- **[Update your env file, it now has our dev reCAPTCHA key](https://www.notion.so/nwplus/env-0407d7c9fc0849088d738c109ce654fc)**
- No idea how any of this will behave on a Mac, so try running `make dev`. If you get an error, check to see if the error is not already in `functions/README.md`. 
- Try submitting the application, and check your console for a success message, and also check firestore for new documents in the two collections

### CODE REVIEW

**Comment by mingyokim** [comment]
@chamkank 

So getting a lot of these errors:
image

Also, I'm not getting the recaptcha screen where you have to select images. And i feel like this recaptcha option is a bit lengthy, would it be possible to use the one where you just have to click a checkbox?

**Comment by chamkank** [comment]
1. Hmmm not sure what those errors are, at what point do they happen?

2. I selected the invisible reCAPTCHA , so the UI is affected only if it thinks you're a bot and challenges you (i.e. the submit button is basically the checkbox). So in theory most applicants won't have to do any extra work. The reCAPTCHA checkbox behaves the same way unfortunately, you can still be challenged if it thinks you're a bot.

**Comment by mingyokim** [comment]
1. It happens almost immediately after I go to `/application/hacker`
2. Ok thats fine with me!

**Comment by mingyokim** [comment]
Also i've noticed that the success message appears like ~5 seconds after you submit. Is there a plan for displaying some kind of loading message/page during that time?

**Comment by chamkank** [comment]
I just gave the loading message a shot but no luck, I don't think I'm handling the state right in `PageTemplate.js`. 😕 I'm open a ticket for it #159

**Comment by chamkank** [comment]
- redirecting/loading/error handling should be covered by #159 
- Just fixed everything, the whole thing should work now
- Constraints still need to be updated (#158)

**Comment by chamkank** [comment]
Oops forgot to store each user doc under the same ID, will fix with a new PR

**Pull request merged**
